import Navbar from '@/Components/Navbar/Page'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const navMenu= ["Home", "About", "Services", "Contact"]
  const navMenu=[{"name":"Home", "link":"/"}, {"name":"About", "link":"/about"}, {"name":"Services", "link":"/services"}, {"name":"Contact", "link":"/contact"}]
  return (
    <html lang="en">
      
      <body className={inter.className}>
      
      <Navbar navMenu={navMenu}/>
      <div>{children}</div>
      <Footer/>
      </body>
    </html>
  )
}
